name: New-jorg
favicon: null
layout_spectrum: 0.75673
typography_spectrum: 0.75135
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f7e5c'
    - '#232323'
    - '#205d47'
    - '#1f6e51'
    - '#214136'
  brandStrength: 0.15663674008101225
  lightness: 0.3115109750069678
  saturation: 0.5355539235752076
  rhythmicContrast: 0.10590811306610703
purpose: []
