name: New-jorg
favicon: null
layout_spectrum: 0.25121
typography_spectrum: 0.75135
title: PlayGround
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f7e5c'
    - '#232323'
    - '#205d47'
    - '#1f6e51'
    - '#214136'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
